function wiki(file) {
  return `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=2000`;
}

function inat(id, ext) {
  return `https://inaturalist-open-data.s3.amazonaws.com/photos/${id}/original.${ext || "jpg"}`;
}

function inatAll(id, ext) {
  return `https://static.inaturalist.org/photos/${id}/original.${ext || "jpg"}`;
}

function wild(item) {
  const name = item.name;
  const short = name.replace(/^Monstera /, "");
  return {
    family: item.family || "Araceae",
    difficulty: item.difficulty || "Peu cultivée",
    light: item.light || "Lumière vive indirecte",
    water: item.water || "Terreau aéré ; le haut doit sécher",
    image: item.image || "",
    credit: item.credit || "Pas de photo libre vérifiée pour cette fiche.",
    size: item.size || "Liane de forêt ; peu de mesures en pot",
    kind: item.kind || "species",
    common: item.common && item.common.length ? item.common : [short],
    traits: item.traits || ["Espèce acceptée (Kew)"],
    id: item.id,
    name,
    origin: item.origin,
    summary: item.summary,
    description: item.description,
  };
}

function forestNote(where) {
  return `Espèce acceptée par Kew (POWO). ${where} Comme les autres Monsteras, c’est une liane de forêt tropicale : elle germe souvent au sol, cherche un tronc, grimpe, et sa feuille jeune ne ressemble pas toujours à la feuille adulte. On la connaît surtout par les herbiers et les révisions de Croat, Cedeño, Zuluaga, Ortiz et collègues. Rarement en jardinerie : si un vendeur utilise ce nom, demande d’où vient le clone.`;
}

window.MONSTERA_CATALOG = [
  wild({
    id: "deliciosa",
    name: "Monstera deliciosa",
    common: ["Faux philodendron", "Swiss cheese plant", "Costilla de Adán"],
    origin: "Mexique (Veracruz, Oaxaca, Chiapas) → Guatemala selon Kew ; largement cultivée et naturalisée sous les tropiques",
    size: "2–3 m en intérieur ; jusqu’à ~20 m en forêt",
    difficulty: "Facile",
    light: "Lumière vive indirecte (pas le plein soleil)",
    water: "Quand le haut du terreau a un peu séché",
    image: wiki("Monstera deliciosa (Monaco).jpg"),
    credit: "Wikimedia Commons",
    summary:
      "C’est la Monstera que tout le monde reconnaît : grandes feuilles en cœur qui se découpent sur les bords, puis se percent. Celle des salons — pas celle qui donne son nom au genre.",
    description:
      "Si tu imagines une Monstera, c’est presque toujours celle-ci. Petite, sa feuille est entière, comme un cœur. En grandissant, avec de la lumière et un tuteur, le bord se fend, puis des trous apparaissent au milieu. En forêt elle grimpe très haut. Chez toi, compte plutôt 2 ou 3 mètres. Le fruit mûr rappelle souvent l’ananas ; encore vert, il irrite (oxalates). Ce n’est pas l’espèce « type » du genre : ce rôle revient à adansonii.",
    traits: ["Espèce acceptée", "La plus cultivée", "Fentes + trous", "Fruit mûr seulement"],
  }),
  wild({
    id: "adansonii",
    name: "Monstera adansonii",
    common: ["Monkey mask", "Swiss cheese vine"],
    origin: "Amérique centrale et du Sud, Antilles — large aire",
    size: "1–2 m en pot ; plus longue si elle grimpe",
    difficulty: "Facile",
    light: "Lumière moyenne à vive, sans soleil brûlant",
    water: "Légèrement humide, jamais d’eau stagnante",
    image: wiki("Monstera adansonii - Mickaël Schauli - 1.jpg"),
    credit: "Wikimedia Commons / Mickaël Schauli",
    summary:
      "La petite liane aux trous au milieu de la feuille. Très courante, et souvent vendue à tort sous le nom obliqua. C’est l’espèce type du genre.",
    description:
      "Regarde le centre de la feuille : adansonii est trouée comme un fromage, sans les grandes fentes de deliciosa. Facile, elle grimpe bien. Kew et l’IPNI en font l’espèce de référence du genre, même si deliciosa est plus célèbre. Quatre sous-espèces existent. En magasin, l’étiquette « obliqua » lui est souvent collée.",
    traits: ["Espèce type", "Très courante", "Trous au centre"],
  }),
  wild({
    id: "adansonii-adansonii",
    name: "Monstera adansonii subsp. adansonii",
    common: ["Sous-espèce type"],
    origin: "Aire antillaise / nord de l’aire d’adansonii (Mayo & Andrade)",
    kind: "subspecies",
    image: inat(610007805),
    credit: "iNaturalist — sous-espèce type",
    summary: "La sous-espèce qui porte le même nom que l’espèce. Les quatre sous-espèces se ressemblent : on les sépare surtout à l’aire et aux détails d’herbier.",
    description:
      "Mayo et Andrade ont regroupé d’anciens noms (dont des « espèces » de Schott) en quatre sous-espèces d’adansonii. Celle-ci est la forme type. En pot, tu ne peux presque jamais les distinguer à l’œil : trop de clones horticoles mélangés. Ce n’est pas une cinquième espèce.",
    traits: ["Sous-espèce", "Même espèce qu’adansonii"],
  }),
  wild({
    id: "adansonii-blanchetii",
    name: "Monstera adansonii subsp. blanchetii",
    common: ["blanchetii"],
    origin: "Surtout le Brésil oriental (Mayo & Andrade)",
    image: inat(606514798),
    credit: "iNaturalist — subsp. blanchetii",
    kind: "subspecies",
    summary: "Ancien nom élevé au rang d’espèce par Schott, aujourd’hui une sous-espèce d’adansonii, surtout à l’est de l’Amérique du Sud.",
    description:
      "Schott l’avait appelée comme une espèce à part. Mayo et Andrade l’ont ramenée sous adansonii. Feuille toujours trouée au centre. Le nom « blanchetii » sur une étiquette de boutique ne prouve pas l’origine brésilienne.",
    traits: ["Sous-espèce", "Brésil (aire historique)"],
  }),
  wild({
    id: "adansonii-klotzschiana",
    name: "Monstera adansonii subsp. klotzschiana",
    common: ["klotzschiana"],
    origin: "Amérique du Sud (Mayo & Andrade)",
    image: inat(604861987),
    credit: "iNaturalist — subsp. klotzschiana",
    kind: "subspecies",
    summary: "Autre ancien « Monstera klotzschiana », maintenant une sous-espèce d’adansonii.",
    description:
      "Même histoire : un nom de Schott, puis un rang plus bas. En culture, les « wide form » et « narrow form » sont des noms de pépinière, pas ces sous-espèces.",
    traits: ["Sous-espèce"],
  }),
  wild({
    id: "adansonii-laniata",
    name: "Monstera adansonii subsp. laniata",
    common: ["laniata"],
    origin: "Nord de l’Amérique du Sud (Mayo & Andrade)",
    image: inat(613483648),
    credit: "iNaturalist — subsp. laniata",
    kind: "subspecies",
    summary: "Quatrième sous-espèce d’adansonii. Encore une fois : pas une espèce séparée.",
    description:
      "Le limbe reste celui d’une adansonii (trous au milieu). Utile pour les flores, presque inutile pour choisir un godet en ville.",
    traits: ["Sous-espèce"],
  }),
  wild({
    id: "obliqua",
    name: "Monstera obliqua",
    common: ["Obliqua", "Obliqua Peru", "ultra ajourée"],
    origin: "Costa Rica → Amérique du Sud tropicale et Trinité (Kew)",
    size: "Souvent plus petite que deliciosa ; feuilles fréquemment 10–25 cm chez Madison",
    difficulty: "Facile pour le plant de magasin",
    image: wiki('Monstera Obliqua "Peru" - Mickaël Schauli - 2.jpg'),
    credit: "Wikimedia Commons / Mickaël Schauli",
    summary:
      "Oui, l’espèce existe. Non, le pot à 15 € « Obliqua Peru » n’est pas une relique. Souvent, c’est une adansonii avec une autre étiquette.",
    description:
      "On raconte encore qu’obliqua n’aurait été vue que 17 fois. C’est une vieille idée (Madison 1977) : l’espèce a une large aire. Le godet « ultra ajouré » de jardinerie n’est pas une rareté, et le nom est souvent celui d’une adansonii. Les deux ont des trous au milieu, pas les fentes de deliciosa.",
    traits: ["Espèce acceptée", "Nom souvent mélangé"],
  }),
  wild({
    id: "acuminata",
    name: "Monstera acuminata",
    common: ["Shingle plant", "plante tuile"],
    origin: "Mexique → Amérique centrale ; l’espèce la plus au nord du genre",
    image: wiki("Monstera acuminata in Belize.jpg"),
    credit: "Wikimedia Commons",
    size: "Jeune : plaquée au tronc ; adulte : grandes feuilles, allure proche d’une deliciosa",
    difficulty: "Intermédiaire",
    summary:
      "Au nord du genre. Jeune, elle plaque des feuilles épaisses comme des tuiles. Plus haut, elle change et rappelle une deliciosa.",
    description:
      "Kew l’accepte. Elle germe au sol, rampe, puis grimpe. Les jeunes feuilles se chevauchent (shingling). L’adulte, plus haut, a des feuilles bien plus grandes : c’est le dimorphisme classique. Des noms comme belizensis, chiapensis, dimidiata, grandifolia sont des synonymes. Ce n’est pas une deliciosa, même si l’adulte peut tromper.",
    traits: ["Espèce acceptée", "Shingling", "La plus septentrionale"],
  }),
  wild({
    id: "punctulata",
    name: "Monstera punctulata",
    common: ["punctulata"],
    origin: "Sud du Mexique → Belize, Guatemala, Costa Rica, Panama",
    image: wiki("Monstera punctulata 112910687.jpg"),
    credit: "Wikimedia Commons / iNaturalist",
    summary:
      "De grandes feuilles percées de nombreux petits trous, comme un pointillé. Espèce d’Amérique centrale, pas un cultivar.",
    description:
      "Acceptée par Kew. Le nom dit « ponctuée » : le limbe adulte est souvent criblé de petites ouvertures, différent des grandes fentes de deliciosa. Forêt humide du sud du Mexique à Panama. Peu courante en magasin européen.",
    traits: ["Espèce acceptée", "Nombreux petits trous"],
  }),
  wild({
    id: "tenuis",
    name: "Monstera tenuis",
    common: ["tenuis"],
    origin: "Sud-est du Nicaragua → ouest du Panama",
    image: wiki("Monstera tenuis 108347272.jpg"),
    credit: "Wikimedia Commons / iNaturalist",
    summary:
      "Adulte, la feuille est découpée en lanières étroites. Une vraie espèce d’Amérique centrale, pas un surnom de deliciosa.",
    description:
      "Acceptée par Kew. « Tenuis » = mince : les lobes adultes sont souvent très découpés. Aire assez étroite (Nicaragua–Panama). On la confond parfois avec pinnatipartita ; les flores locales les séparent. Rare en culture hors collections.",
    traits: ["Espèce acceptée", "Feuille très découpée"],
  }),
  wild({
    id: "tuberculata",
    name: "Monstera tuberculata",
    common: ["tuberculata"],
    origin: "Sud du Mexique → Belize, Guatemala, Nicaragua, Costa Rica, Panama",
    image: wiki("Monstera tuberculata 148867607.jpg"),
    credit: "Wikimedia Commons / iNaturalist",
    size: "Plutôt petite ; souvent plaquée au support",
    summary:
      "Petite liane, souvent collée au tronc. Deux variétés sont reconnues (tuberculata et brevinoda).",
    description:
      "Acceptée par Kew. Moins « salon » que deliciosa : feuilles plus petites, port souvent plaqué. Madison a distingué var. brevinoda. Encore une fois, le jeune et l’adulte ne se ressemblent pas forcément.",
    traits: ["Espèce acceptée", "Petite", "Deux variétés"],
  }),
  wild({
    id: "tuberculata-brevinoda",
    name: "Monstera tuberculata var. brevinoda",
    common: ["brevinoda"],
    origin: "Amérique centrale (Madison)",
    image: inat(639420230),
    credit: "iNaturalist — var. brevinoda",
    kind: "subspecies",
    summary: "Variété de tuberculata à entrenœuds plus courts. Ce n’est pas une espèce à part.",
    description:
      "Madison a séparé cette variété sur des détails de tige. Kew garde le nom sous tuberculata. En pot, inutile de payer « une espèce rare » pour ce rang.",
    traits: ["Variété", "Pas une espèce"],
  }),
  wild({
    id: "epipremnoides",
    name: "Monstera epipremnoides",
    common: ["epipremnoides vraie"],
    origin: "Costa Rica, Panama",
    image: wiki("Monstera epipremnoides.jpg"),
    credit: "Wikimedia Commons",
    summary:
      "Vraie espèce de montagne d’Amérique centrale. Ce n’est pas le clone très troué vendu ‘Esqueleto’.",
    description:
      "Engl. l’a décrite ; Kew l’accepte. Elle pousse au Costa Rica et au Panama. Les collectionneurs ont collé ce nom pendant des années sur un clone de serre aux fenêtres énormes. Après comparaison avec les populations sauvages, ce clone est devenu le cultivar ‘Esqueleto’. Si tu veux l’espèce, il faut une origine documentée, pas un surnom de forum.",
    traits: ["Espèce acceptée", "Pas ‘Esqueleto’"],
  }),
  wild({
    id: "lechleriana",
    name: "Monstera lechleriana",
    common: ["lechleriana"],
    origin: "Amérique du Sud andine et amazonienne (large)",
    image: wiki("Monstera lechleriana.jpg"),
    credit: "Wikimedia Commons",
    difficulty: "Intermédiaire",
    summary:
      "Grande liane d’Amérique du Sud, souvent trouée. Beaucoup de plantes de collection lui ressemblent — y compris, selon certains, le clone ‘Esqueleto’.",
    description:
      "Schott ; nom accepté. Feuilles souvent allongées, perforées. Plus présente en culture que la plupart des espèces « nouvelles » d’Amérique centrale. On la photographie souvent à la place d’autres noms. Ce n’est ni deliciosa, ni adansonii.",
    traits: ["Espèce acceptée", "Souvent en collection"],
  }),
  wild({
    id: "dubia",
    name: "Monstera dubia",
    common: ["Dubia", "shingling monstera"],
    origin: "Amérique centrale et du Sud (Costa Rica, Panama, Amazonie, Trinité…)",
    size: "Plaquée au support jeune ; plus grande plus haut",
    difficulty: "Intermédiaire",
    image: wiki("Monstera dubia (Kunth) Engl. & K.Krause - par Mickael Schauli.jpg"),
    credit: "Wikimedia Commons / Mickaël Schauli",
    summary:
      "Deux plantes en une. Petite, elle plaque des feuilles argentées. Grande, elle change complètement de tête.",
    description:
      "Acceptée. Fort dimorphisme. Sans tuteur elle reste souvent juvénile. L’argenté qui part en hauteur n’est pas une maladie : c’est l’âge adulte.",
    traits: ["Espèce acceptée", "Dimorphisme", "Shingling"],
  }),
  wild({
    id: "siltepecana",
    name: "Monstera siltepecana",
    common: ["Siltepecana", "Silver Monstera"],
    origin: "Est et sud du Mexique → Nicaragua (Kew)",
    difficulty: "Facile",
    image: wiki("Monstera siltepecana (Silver Monstera) Tropical Houseplant.jpg"),
    credit: "Wikimedia Commons",
    summary:
      "Jeune, un éclat argenté sur des feuilles allongées. En grimpant, elle verdit et peut se percer.",
    description:
      "Matuda ; acceptée. L’argenté n’est pas une panachure de cultivar. Aire : Mexique à Nicaragua, pas « toute l’Amérique ».",
    traits: ["Espèce acceptée", "Argent juvénile"],
  }),
  wild({
    id: "standleyana",
    name: "Monstera standleyana",
    common: ["Standleyana", "vendue « Philodendron Cobra »"],
    origin: "Sud-est du Nicaragua → nord-ouest de la Colombie (Kew)",
    difficulty: "Facile",
    image: inat(14425738, "jpeg"),
    credit: "iNaturalist",
    summary:
      "Feuilles longues et étroites, souvent sans trou. L’étiquette « Philodendron Cobra » est fausse : c’est bien une Monstera.",
    description:
      "Bunting ; acceptée. Limbe lancéolé, le plus souvent entier. Les formes crème ou jaunes sont des sélections.",
    traits: ["Espèce acceptée", "Pas un Philodendron"],
  }),
  wild({
    id: "pinnatipartita",
    name: "Monstera pinnatipartita",
    common: ["Pinnatipartita"],
    origin: "Costa Rica, Panama, Colombie, Équateur, Venezuela, Bolivie (Kew)",
    difficulty: "Intermédiaire",
    image: wiki("Monstera pinnatipartita in Colombia.jpg"),
    credit: "Wikimedia Commons",
    summary:
      "Adulte, la feuille est découpée jusqu’à la nervure, comme une main. Ni deliciosa, ni « Monstera Peru ».",
    description:
      "Schott ; acceptée. Jeune feuille simple ; en grimpant, lobes pennés. Ne pas l’appeler « Monstera Peru » (en général un philodendron).",
    traits: ["Espèce acceptée", "Feuille pennée"],
  }),
  wild({
    id: "subpinnata",
    name: "Monstera subpinnata",
    common: ["subpinnata"],
    origin: "Ouest de l’Amérique du Sud (Andes / piémont — Kew)",
    image: inat(21831894),
    credit: "iNaturalist",
    summary:
      "Cousine à feuille plus ou moins pennée, plus au sud que beaucoup d’espèces d’Amérique centrale.",
    description:
      "Acceptée (Engl. d’après Schott). Moins célèbre que pinnatipartita. Liane de forêt andine et amazonienne. Peu de plants honnêtement étiquetés en Europe.",
    traits: ["Espèce acceptée"],
  }),
  wild({
    id: "dissecta",
    name: "Monstera dissecta",
    common: ["dissecta"],
    origin: "Amérique centrale (Croat & Grayum)",
    image: wiki("Monstera dissecta 254263582.jpg"),
    credit: "Wikimedia Commons / iNaturalist",
    summary: "Feuille adulte très découpée. Nom accepté après recombinaison dans Monstera.",
    description:
      "Autrefois rangée ailleurs ; Croat et Grayum l’ont placée dans Monstera. « Dissecta » décrit le limbe découpé. À ne pas confondre avec toutes les deliciosa très fenêtrées des boutiques.",
    traits: ["Espèce acceptée"],
  }),
  wild({
    id: "costaricensis",
    name: "Monstera costaricensis",
    common: ["costaricensis"],
    origin: "Costa Rica",
    image: inat(14656550, "jpeg"),
    credit: "iNaturalist",
    summary: "Espèce du Costa Rica, acceptée après transfert dans Monstera par Croat et Grayum.",
    description: forestNote("Endémique ou quasi endémique du Costa Rica."),
    traits: ["Espèce acceptée", "Costa Rica"],
  }),
  wild({
    id: "acacoyaguensis",
    name: "Monstera acacoyaguensis",
    common: ["acacoyaguensis"],
    origin: "Mexique (Chiapas) et Guatemala (Matuda)",
    image: inat(115128248, "jpeg"),
    credit: "iNaturalist",
    summary: "Espèce de Matuda, sud du Mexique / Guatemala. Presque jamais en jardinerie.",
    description: forestNote("Décrite d’Acacoyagua et des forêts voisines."),
    traits: ["Espèce acceptée", "Mexique–Guatemala"],
  }),
  wild({
    id: "egregia",
    name: "Monstera egregia",
    common: ["egregia"],
    origin: "Mexique",
    image: wiki("Monstera egregia in Mexico.jpg"),
    credit: "Wikimedia Commons",
    summary: "Ancienne espèce de Schott, encore acceptée, du Mexique.",
    description: forestNote("Peu d’images de plantes vivantes circulent sous un nom sûr."),
    traits: ["Espèce acceptée", "Mexique"],
  }),
  wild({
    id: "tacanaensis",
    name: "Monstera tacanaensis",
    common: ["tacanaensis"],
    origin: "Volcan Tacaná : Mexique / Guatemala (Matuda)",
    image: inat(181912576),
    credit: "iNaturalist",
    summary: "Nommé d’après le Tacaná. Espèce de montagne, acceptée par Kew.",
    description: forestNote("Aire très localisée autour du volcan."),
    traits: ["Espèce acceptée", "Aire étroite"],
  }),
  wild({
    id: "florescanoana",
    name: "Monstera florescanoana",
    common: ["florescanoana"],
    origin: "Mexique (décrite par Croat, Krömer & Acebey)",
    image: inat(14550067, "jpeg"),
    credit: "iNaturalist",
    summary: "Espèce mexicaine récemment circonscrite. Pas un nom de boutique.",
    description: forestNote("Publication moderne, basée sur des spécimens de terrain."),
    traits: ["Espèce acceptée", "Mexique"],
  }),
  wild({
    id: "guzmanjacobiae",
    name: "Monstera guzmanjacobiae",
    common: ["guzmanjacobiae"],
    origin: "Mexique",
    image: inat(119076308, "jpeg"),
    credit: "iNaturalist",
    summary: "Espèce mexicaine dédiée, acceptée. Connue des flores, pas des rayons.",
    description: forestNote("Décrite récemment (Díaz Jiménez, Cedeño, Zuluaga, Aguilar-Rodríguez)."),
    traits: ["Espèce acceptée", "Mexique"],
  }),
  wild({
    id: "maderaverde",
    name: "Monstera maderaverde",
    common: ["maderaverde"],
    origin: "Honduras (Grayum & Karney)",
    image: "https://images.mobot.org/tropicosimages3/detailimages/TropicosImages2/100207000/64220C5D-D02A-4823-A062-4DD9A7B14BAB.jpg",
    credit: "Missouri Botanical Garden / Tropicos",
    summary: "Espèce hondurienne. Le nom vient d’une localité / forêt.",
    description: forestNote("Aire connue surtout du Honduras."),
    traits: ["Espèce acceptée", "Honduras"],
  }),
  wild({
    id: "luteynii",
    name: "Monstera luteynii",
    common: ["luteynii"],
    origin: "Costa Rica (Madison)",
    image: inat(513702068),
    credit: "iNaturalist",
    summary: "Décrite par Madison, Costa Rica. Acceptée.",
    description: forestNote("Une des espèces « classiques » de la monographie de Madison, encore retenue."),
    traits: ["Espèce acceptée", "Costa Rica"],
  }),
  wild({
    id: "oreophila",
    name: "Monstera oreophila",
    common: ["oreophila"],
    origin: "Montagnes du Costa Rica (Madison)",
    image: inat(173356035, "jpeg"),
    credit: "iNaturalist",
    summary: "« Qui aime la montagne ». Espèce d’altitude du Costa Rica.",
    description: forestNote("Pas une plante de rebord de fenêtre tropical bas."),
    traits: ["Espèce acceptée", "Montagne"],
  }),
  wild({
    id: "membranacea",
    name: "Monstera membranacea",
    common: ["membranacea"],
    origin: "Costa Rica (Madison)",
    image: wiki("Monstera membranacea.jpg"),
    credit: "Wikimedia Commons",
    summary: "Feuille plutôt mince (le nom le dit). Espèce costaricienne acceptée.",
    description: forestNote("Madison l’a séparée sur la texture du limbe, entre autres caractères."),
    traits: ["Espèce acceptée", "Costa Rica"],
  }),
  wild({
    id: "minima",
    name: "Monstera minima",
    common: ["minima"],
    origin: "Panama (Madison)",
    image: inat(649904181),
    credit: "iNaturalist",
    size: "Parmi les plus petites du genre",
    summary: "L’une des plus petites Monsteras décrites. Panama.",
    description:
      "Madison l’a nommée pour sa petite taille. Kew l’accepte. Ce n’est pas une « mini Monstera » de magasin : ce surnom désigne en général Rhaphidophora tetrasperma, qui n’est pas une Monstera.",
    traits: ["Espèce acceptée", "Très petite", "Pas la « mini Monstera » des shops"],
  }),
  wild({
    id: "pittieri",
    name: "Monstera pittieri",
    common: ["pittieri"],
    origin: "Costa Rica, Panama (Engl.)",
    image: inat(109135403),
    credit: "iNaturalist",
    summary: "Ancienne espèce d’Engler, toujours acceptée, sud de l’Amérique centrale.",
    description: forestNote("Nommé d’après le botaniste Pittier."),
    traits: ["Espèce acceptée"],
  }),
  wild({
    id: "filamentosa",
    name: "Monstera filamentosa",
    common: ["filamentosa"],
    origin: "Costa Rica, Panama (Croat & Grayum)",
    image: inat(50942207, "jpeg"),
    credit: "iNaturalist",
    summary: "Espèce d’Amérique centrale à caractères filamenteux sur l’inflorescence / le limbe selon la diagnose.",
    description: forestNote("Décrite dans le cadre des flores mésoaméricaines."),
    traits: ["Espèce acceptée"],
  }),
  wild({
    id: "buseyi",
    name: "Monstera buseyi",
    common: ["buseyi"],
    origin: "Costa Rica (Croat & Grayum)",
    image: inat(343374277),
    credit: "iNaturalist",
    summary: "Espèce costaricienne dédiée. Acceptée.",
    description: forestNote("Peu circulée hors herbiers."),
    traits: ["Espèce acceptée", "Costa Rica"],
  }),
  wild({
    id: "glaucescens",
    name: "Monstera glaucescens",
    common: ["glaucescens"],
    origin: "Costa Rica, Panama (Croat & Grayum)",
    image: wiki("Monstera glaucescens.png"),
    credit: "Wikimedia Commons",
    summary: "Jeune feuillage souvent un peu glauque (bleu-vert). Espèce acceptée.",
    description: forestNote("Le nom décrit une pruine / teinte, pas une panachure de cultivar."),
    traits: ["Espèce acceptée"],
  }),
  wild({
    id: "lentii",
    name: "Monstera lentii",
    common: ["lentii"],
    origin: "Costa Rica, Panama (Croat & Grayum)",
    image: wiki("Monstera lentii 112911286.jpg"),
    credit: "Wikimedia Commons / iNaturalist",
    summary: "Espèce d’Amérique centrale, acceptée, dédiée à Lent.",
    description: forestNote(""),
    traits: ["Espèce acceptée"],
  }),
  wild({
    id: "molinae",
    name: "Monstera molinae",
    common: ["molinae"],
    origin: "Costa Rica, Panama (Croat & Grayum)",
    image: inat(357553523),
    credit: "iNaturalist",
    summary: "Encore une espèce mésoaméricaine des flores de Croat et Grayum.",
    description: forestNote(""),
    traits: ["Espèce acceptée"],
  }),
  wild({
    id: "monteverdensis",
    name: "Monstera monteverdensis",
    common: ["monteverdensis"],
    origin: "Région de Monteverde, Costa Rica (Cedeño & Croat)",
    image: wiki("Monstera monteverdensis in Costa Rica.jpg"),
    credit: "Wikimedia Commons",
    summary: "Décrite de Monteverde. Aire étroite, acceptée.",
    description: forestNote("Forêts nuageuses du Costa Rica."),
    traits: ["Espèce acceptée", "Costa Rica"],
  }),
  wild({
    id: "gambensis",
    name: "Monstera gambensis",
    common: ["gambensis"],
    origin: "Costa Rica (Cedeño & Blanco)",
    image: wiki("Vital parts of a Monstera gambensis (cropped).jpg"),
    credit: "Wikimedia Commons",
    summary: "Espèce costaricienne récente, acceptée par Kew.",
    description: forestNote("Publication du XXIe siècle : on ne lui invente pas une vie de plante d’appartement."),
    traits: ["Espèce acceptée", "Costa Rica"],
  }),
  wild({
    id: "juliusii",
    name: "Monstera juliusii",
    common: ["juliusii"],
    origin: "Costa Rica (Cedeño & Croat)",
    image: inat(693069942),
    credit: "iNaturalist",
    summary: "Espèce dédiée, Costa Rica. Acceptée.",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Costa Rica"],
  }),
  wild({
    id: "alfaroi",
    name: "Monstera alfaroi",
    common: ["alfaroi"],
    image: "https://static.inaturalist.org/photos/169485168/original.jpg",
    credit: "iNaturalist / LostInCR",
    origin: "Costa Rica (Croat & Cedeño, 2020)",
    summary: "Décrite en 2020. Costa Rica.",
    description: forestNote("Nordic Journal of Botany."),
    traits: ["Espèce acceptée", "Décrite en 2020"],
  }),
  wild({
    id: "croatii",
    name: "Monstera croatii",
    common: ["croatii"],
    origin: "Amérique centrale (Cedeño & Hay)",
    image: inat(610271086),
    credit: "iNaturalist",
    summary: "Dédiée à Tom Croat, spécialiste des Aracées. Acceptée.",
    description: forestNote("Le nom honore l’auteur de dizaines d’espèces du genre."),
    traits: ["Espèce acceptée"],
  }),
  wild({
    id: "limitaris",
    name: "Monstera limitaris",
    common: ["limitaris"],
    origin: "Frontière Costa Rica–Panama (Cedeño)",
    image: inat(452509113, "jpeg"),
    credit: "iNaturalist",
    summary: "« Des confins ». Espèce de la frontière, acceptée.",
    description: forestNote("Aire très localisée."),
    traits: ["Espèce acceptée", "Aire étroite"],
  }),
  wild({
    id: "tablasensis",
    name: "Monstera tablasensis",
    common: ["tablasensis"],
    origin: "Costa Rica (Cedeño)",
    image: inatAll(269122672),
    credit: "iNaturalist",
    summary: "Nommé d’après une localité costaricienne (Tablas).",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Costa Rica"],
  }),
  wild({
    id: "tarrazuensis",
    name: "Monstera tarrazuensis",
    common: ["tarrazuensis"],
    origin: "Tarrazú, Costa Rica (Croat & Cedeño)",
    image: inat(724942390),
    credit: "iNaturalist",
    summary: "Espèce de Tarrazú. Acceptée.",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Costa Rica"],
  }),
  wild({
    id: "wilsoniensis",
    name: "Monstera wilsoniensis",
    common: ["wilsoniensis"],
    origin: "Costa Rica (Cedeño & Grayum)",
    image: inat(109073480, "jpeg"),
    credit: "iNaturalist",
    summary: "Espèce costaricienne acceptée, localité Wilson.",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Costa Rica"],
  }),
  wild({
    id: "mittermeieri",
    name: "Monstera mittermeieri",
    common: ["mittermeieri"],
    origin: "Costa Rica (Cedeño)",
    summary: "Espèce dédiée, Costa Rica. Acceptée par Kew.",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Costa Rica"],
  }),
  wild({
    id: "bocatorensis",
    name: "Monstera bocatorensis",
    common: ["bocatorensis"],
    origin: "Bocas del Toro, Panama (Croat & Cedeño)",
    image: inat(170642058, "jpeg"),
    credit: "iNaturalist",
    summary: "Du nord-ouest du Panama. Acceptée.",
    description: forestNote("Province de Bocas del Toro."),
    traits: ["Espèce acceptée", "Panama"],
  }),
  wild({
    id: "alcirana",
    name: "Monstera alcirana",
    common: ["alcirana"],
    image: "https://inaturalist-open-data.s3.amazonaws.com/photos/180812156/original.jpg",
    credit: "iNaturalist / Carlos Sanchez",
    origin: "Panama (Croat, Cedeño, Zuluaga & Ortiz, 2020)",
    summary: "Décrite en 2020 au Panama.",
    description: forestNote("Webbia 75."),
    traits: ["Espèce acceptée", "Panama"],
  }),
  wild({
    id: "donosoensis",
    name: "Monstera donosoensis",
    common: ["donosoensis"],
    origin: "Donoso, Panama (Croat, Cedeño & Ortiz)",
    image: inat(234572560, "jpeg"),
    credit: "iNaturalist",
    summary: "District de Donoso, Panama. Acceptée.",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Panama"],
  }),
  wild({
    id: "gentryi",
    name: "Monstera gentryi",
    common: ["gentryi"],
    origin: "Panama (Croat, Cedeño & Ortiz)",
    image: "https://images.mobot.org/tropicosimages6/detailimages/TropicosImagesVol6/102617000/184A55A4-B372-4407-89BE-A6A7BFCF0713.jpg",
    credit: "Missouri Botanical Garden / Tropicos",
    summary: "Dédiée à Alwyn Gentry. Panama.",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Panama"],
  }),
  wild({
    id: "gigas",
    name: "Monstera gigas",
    common: ["gigas"],
    origin: "Panama, région de Fortuna (décrite 2021)",
    image: inat(178852883, "jpeg"),
    credit: "iNaturalist — M. gigas (Panama), pas une deliciosa géante",
    size: "Les plus grandes feuilles mesurées dans le genre (jusqu’à ~3 m de long, littérature)",
    summary:
      "Le géant. Décrite en 2021 : feuilles parmi les plus longues du genre. Panama, pas un salon.",
    description:
      "Croat, Zuluaga, Cedeño et Ortiz, Webbia 2021. L’épithète grecque « géant » vise la taille du limbe — Wikipedia et IPNI le relient aux plus grandes feuilles du genre. Forêt montagnarde panaméenne. Ce n’est pas une deliciosa « qui a bien poussé ».",
    traits: ["Espèce acceptée", "Feuilles géantes", "Panama"],
  }),
  wild({
    id: "titanum",
    name: "Monstera titanum",
    common: ["titanum"],
    origin: "Ouest du Panama (Bocas del Toro, Chiriquí, Fortuna…)",
    image: inat(113842337, "jpeg"),
    credit: "iNaturalist",
    summary: "Autre grande espèce panaméenne, décrite avec Cedeño et Ortiz. Pas le titan arum (Amorphophallus).",
    description:
      "Le nom rappelle un titan, mais ce n’est pas Amorphophallus titanum. Liane de montagne à l’ouest du Panama, spécimens à MO et PMA. Acceptée par Kew.",
    traits: ["Espèce acceptée", "Panama"],
  }),
  wild({
    id: "colossica",
    name: "Monstera colossica",
    common: ["colossica"],
    origin: "Panama (Cedeño & Ortiz)",
    summary: "Encore un nom qui dit « colossal ». Espèce panaméenne acceptée.",
    description: forestNote("Ne pas confondre avec gigas ou titanum : trois espèces, trois diagnoses."),
    traits: ["Espèce acceptée", "Panama"],
  }),
  wild({
    id: "corana",
    name: "Monstera corana",
    common: ["corana"],
    origin: "Panama (Cedeño & Ortiz)",
    summary: "Espèce panaméenne récente. Acceptée.",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Panama"],
  }),
  wild({
    id: "panamensis",
    name: "Monstera panamensis",
    common: ["panamensis"],
    origin: "Panama (Cedeño & Ortiz)",
    image: inat(252966463, "jpeg"),
    credit: "iNaturalist",
    summary: "Le nom dit l’origine. Acceptée par Kew.",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Panama"],
  }),
  wild({
    id: "cedenoi",
    name: "Monstera cedenoi",
    common: ["cedenoi"],
    origin: "Panama (Ortiz, Croat & Hughes)",
    image: inat(346492409, "jpeg"),
    credit: "iNaturalist",
    summary: "Dédiée à Marco Cedeño, spécialiste du genre. Acceptée.",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Panama"],
  }),
  wild({
    id: "coclensis",
    name: "Monstera coclensis",
    common: ["coclensis"],
    origin: "Coclé, Panama (Croat, révision 2024)",
    image: "https://images.mobot.org/tropicosimages4/detailimages/TropicosImagesVol4/101251000/3EC06C3D-4F09-447C-8A44-36CC66FCB324.jpg",
    credit: "Missouri Botanical Garden / Tropicos",
    summary: "Décrite dans la révision d’Amérique centrale (Phytotaxa 2024).",
    description:
      "Croat, Cedeño et Ortiz reconnaissent 52 espèces natives en Amérique centrale dans Phytotaxa 656 (2024). coclensis en est une nouvelle. Kew l’accepte. Forêt de Coclé.",
    traits: ["Espèce acceptée", "Décrite en 2024"],
  }),
  wild({
    id: "ngabensis",
    name: "Monstera ngabensis",
    common: ["ngabensis"],
    origin: "Comarque Ngäbe-Buglé, Panama (Croat, 2024)",
    summary: "Nouvelle espèce 2024, nommée d’après le territoire ngäbe.",
    description: forestNote("Phytotaxa 656. Pas un cultivar."),
    traits: ["Espèce acceptée", "Décrite en 2024"],
  }),
  wild({
    id: "harrisoneorum",
    name: "Monstera harrisoneorum",
    common: ["harrisoneorum"],
    origin: "Amérique centrale (Croat & al., 2024)",
    summary: "Troisième espèce nouvelle de la révision 2024 d’Amérique centrale.",
    description: forestNote("Phytotaxa 656 : harrisoneorum, coclensis, ngabensis."),
    traits: ["Espèce acceptée", "Décrite en 2024"],
  }),
  wild({
    id: "caribaea",
    name: "Monstera caribaea",
    common: ["caribaea"],
    origin: "Caraïbe (Cedeño, Ortiz & Hay) — acceptée Kew",
    summary: "Espèce caribéenne récemment reconnue. Pas « toutes les Monsteras des Antilles ».",
    description: forestNote("Les Antilles ont aussi adansonii. caribaea est un taxon à part, selon Kew."),
    traits: ["Espèce acceptée", "Caraïbe"],
  }),
  wild({
    id: "amargalensis",
    name: "Monstera amargalensis",
    common: ["amargalensis"],
    origin: "Chocó / Amargal, Colombie (Croat & Mora)",
    summary: "Espèce colombienne du Pacifique. Acceptée.",
    description: forestNote("Forêt du Chocó, une des plus humides du monde."),
    traits: ["Espèce acceptée", "Colombie"],
  }),
  wild({
    id: "anomala",
    name: "Monstera anomala",
    common: ["anomala"],
    origin: "Colombie (Zuluaga & Croat, 2018)",
    image: inat(296051301, "jpeg"),
    credit: "iNaturalist",
    summary: "« Anomale » : caractères qui sortaient des cases. Colombie.",
    description: forestNote("Phytotaxa 2018."),
    traits: ["Espèce acceptée", "Colombie"],
  }),
  wild({
    id: "integrifolia",
    name: "Monstera integrifolia",
    common: ["integrifolia"],
    origin: "Colombie (Zuluaga & Croat)",
    image: inat(485250371, "jpeg"),
    credit: "iNaturalist",
    summary: "Feuille souvent entière (sans grandes découpes). Espèce colombienne.",
    description:
      "Le nom dit « feuille entière ». Utile : toutes les Monsteras n’ont pas de trous. Acceptée. Pas une standleyana.",
    traits: ["Espèce acceptée", "Feuille entière"],
  }),
  wild({
    id: "momoi",
    name: "Monstera momoi",
    common: ["momoi"],
    origin: "Colombie (Zuluaga & Cedeño)",
    image: inatAll(592303144),
    credit: "iNaturalist",
    summary: "Espèce colombienne dédiée. Acceptée.",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Colombie"],
  }),
  wild({
    id: "kikiae",
    name: "Monstera kikiae",
    common: ["kikiae"],
    origin: "Colombie (Zuluaga & Cedeño)",
    image: inat(152984924),
    credit: "iNaturalist",
    summary: "Espèce dédiée, Colombie. Acceptée par Kew.",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Colombie"],
  }),
  wild({
    id: "planadensis",
    name: "Monstera planadensis",
    common: ["planadensis"],
    origin: "La Planada, Colombie (Croat)",
    image: inat(219820974),
    credit: "iNaturalist",
    summary: "De la réserve de La Planada, versant pacifique colombien.",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Colombie"],
  }),
  wild({
    id: "xanthospatha",
    name: "Monstera xanthospatha",
    common: ["xanthospatha"],
    origin: "Colombie (Madison)",
    image: inat(344383391),
    credit: "iNaturalist",
    summary: "Spathe jaunâtre (le nom le dit). Espèce de Madison, encore acceptée.",
    description: forestNote("Caractère d’inflorescence, pas de feuille de salon."),
    traits: ["Espèce acceptée", "Colombie"],
  }),
  wild({
    id: "barrieri",
    name: "Monstera barrieri",
    common: ["barrieri"],
    origin: "Guyane (Croat, Moonen & Poncy)",
    image: inat(416048738, "jpeg"),
    credit: "iNaturalist",
    summary: "Espèce de Guyane française, acceptée.",
    description: forestNote("Décrite avec des collectes guyanaises."),
    traits: ["Espèce acceptée", "Guyane"],
  }),
  wild({
    id: "gracilis",
    name: "Monstera gracilis",
    common: ["gracilis"],
    origin: "Nord de l’Amérique du Sud (Engl.)",
    image: inat(310922300),
    credit: "iNaturalist",
    summary: "Ancienne espèce d’Engler, « gracile ». Toujours acceptée.",
    description: forestNote("Ne pas coller ce nom sur n’importe quelle tige fine."),
    traits: ["Espèce acceptée"],
  }),
  wild({
    id: "spruceana",
    name: "Monstera spruceana",
    common: ["spruceana"],
    origin: "Amazonie (Schott / Engl.)",
    image: wiki("Monstera spruceana in Bolivia.jpg"),
    credit: "Wikimedia Commons",
    summary: "Nommé d’après Richard Spruce. Liane amazonienne acceptée.",
    description: forestNote("Bassin amazonien, pas une étiquette de boutique européenne."),
    traits: ["Espèce acceptée", "Amazonie"],
  }),
  wild({
    id: "praetermissa",
    name: "Monstera praetermissa",
    common: ["praetermissa"],
    origin: "Brésil (Gonçalves & Temponi)",
    image: wiki("Monstera praetermissa.jpg"),
    credit: "Wikimedia Commons",
    summary: "« Oubliée » : espèce brésilienne reconnue tard. Acceptée.",
    description: forestNote("Publication moderne, Brésil."),
    traits: ["Espèce acceptée", "Brésil"],
  }),
  wild({
    id: "boliviana",
    name: "Monstera boliviana",
    common: ["boliviana"],
    origin: "Bolivie (Rusby)",
    image: inat(544855965),
    credit: "iNaturalist",
    summary: "Espèce bolivienne ancienne, encore acceptée.",
    description: forestNote("Andes / piémont bolivien selon les spécimens historiques."),
    traits: ["Espèce acceptée", "Bolivie"],
  }),
  wild({
    id: "kessleri",
    name: "Monstera kessleri",
    common: ["kessleri"],
    origin: "Bolivie (Croat)",
    image: inat(285491380, "jpeg"),
    credit: "iNaturalist",
    summary: "Dédiée à Kessler. Bolivie. Acceptée.",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Bolivie"],
  }),
  wild({
    id: "cenepensis",
    name: "Monstera cenepensis",
    common: ["cenepensis"],
    origin: "Río Cenepa, Pérou (Croat)",
    image: "https://images.mobot.org/tropicosimages4/detailimages/TropicosImagesVol4/101255000/6068EE27-2360-434A-80AB-D2E7ED06A0ED.jpg",
    credit: "Missouri Botanical Garden / Tropicos",
    summary: "Espèce péruvienne du Cenepa. Acceptée.",
    description: forestNote("Amazonie péruvienne."),
    traits: ["Espèce acceptée", "Pérou"],
  }),
  wild({
    id: "vasquezii",
    name: "Monstera vasquezii",
    common: ["vasquezii"],
    origin: "Pérou (Croat)",
    summary: "Espèce péruvienne dédiée. Acceptée.",
    description: forestNote(""),
    traits: ["Espèce acceptée", "Pérou"],
  }),
  wild({
    id: "aureopinnata",
    name: "Monstera aureopinnata",
    common: ["aureopinnata"],
    origin: "Pérou (Croat)",
    image: inat(592992520),
    credit: "iNaturalist",
    summary: "Nom qui parle d’or et de lobes pennés. Espèce péruvienne, pas une Aurea de deliciosa.",
    description:
      "Croat, Rodriguésia. Ce n’est pas Monstera deliciosa ‘Aurea’. Espèce sauvage à feuille pennée / teinte mentionnée dans la diagnose. Acceptée.",
    traits: ["Espèce acceptée", "Pérou", "Pas un cultivar Aurea"],
  }),
  wild({
    id: "borsigiana",
    name: "Monstera deliciosa — « Borsigiana »",
    common: ["Borsigiana", "small form"],
    origin: "Même espèce que deliciosa. Kew : Monstera borsigiana = synonyme",
    size: "Souvent vendue plus petite / plus vite",
    difficulty: "Facile",
    kind: "cultivar",
    image: wiki("Monstera deliciosa kz03.jpg"),
    credit: "Wikimedia Commons",
    summary: "Pas une autre espèce : un nom de pépinière pour un format de deliciosa.",
    description:
      "Kew met borsigiana en synonymie de deliciosa. En magasin, « small form » désigne des plants plus compacts. L’étirement entre les nœuds vient surtout du manque de lumière.",
    traits: ["Nom de pépinière", "Synonyme Kew", "deliciosa"],
  }),
  wild({
    id: "thai",
    name: "Monstera deliciosa ‘Thai Constellation’",
    common: ["Thai Constellation", "Thai Con"],
    origin: "Cultivar obtenu in vitro en Thaïlande — pas une espèce sauvage",
    size: "Comme une deliciosa, souvent plus lente",
    difficulty: "Intermédiaire",
    kind: "cultivar",
    image: wiki("Monstera thaicon.jpg"),
    credit: "Wikimedia Commons",
    summary: "Deliciosa tachetée de crème, comme un ciel étoilé. Même espèce, mutation stabilisée en labo.",
    description:
      "Née en culture, pas en forêt. Les taches crème sont en général plus stables que l’Albo. Le crème nourrit peu : croissance plus lente, soleil direct interdit.",
    traits: ["Cultivar", "Panachure crème", "deliciosa"],
  }),
  wild({
    id: "albo",
    name: "Monstera deliciosa ‘Albo Variegata’",
    common: ["Albo"],
    origin: "Mutation chimérique sur deliciosa",
    difficulty: "Avancé",
    kind: "cultivar",
    image: wiki("Monstera deliciosa variegata.jpg"),
    credit: "Wikimedia Commons",
    summary: "Grands secteurs blancs. Superbe, fragile ; le blanc peut partir ou tout envahir.",
    description:
      "Chimère : vert et blanc dans la même plante. Un nœud trop vert peut tout reverter ; trop de blanc, la feuille ne se nourrit plus. Le prix vient de la multiplication, pas d’une forêt secrète.",
    traits: ["Cultivar", "Chimère", "deliciosa"],
  }),
  wild({
    id: "aurea",
    name: "Monstera deliciosa ‘Aurea’",
    common: ["Aurea", "Marmorata", "jaune"],
    origin: "Mutation de deliciosa, secteurs jaunes / dorés",
    image: inatAll(440784742),
    credit: "iNaturalist",
    difficulty: "Avancé",
    kind: "cultivar",
    summary:
      "Comme l’Albo, mais le dessin est jaune d’or, pas blanc. Toujours une deliciosa, pas une espèce.",
    description:
      "Les pépinières disent aussi Marmorata. C’est une chimère : le jaune peut reculer ou envahir. Même soin prudent que l’Albo (lumière vive sans soleil, terreau aéré). Ce n’est pas Monstera aureopinnata, espèce sauvage du Pérou.",
    traits: ["Cultivar", "Panachure jaune", "deliciosa"],
  }),
  wild({
    id: "mint",
    name: "Monstera deliciosa ‘Mint’",
    common: ["Mint"],
    origin: "Sport horticole de deliciosa (vert d’eau)",
    image: "",
    credit: "Pas de photo libre distincte d’un clone Mint.",
    difficulty: "Avancé",
    kind: "cultivar",
    summary:
      "Panachure vert d’eau sur deliciosa. Nom de collectionneurs, pas une espèce Kew.",
    description:
      "Apparue en culture, plus récemment que Thai Con / Albo. Le « mint » est un dégradé vert clair, pas du blanc. Stabilité variable selon les clones. Kew ne liste pas ça comme taxon sauvage.",
    traits: ["Cultivar", "Nom de collection", "deliciosa"],
  }),
  wild({
    id: "esqueleto",
    name: "Monstera ‘Esqueleto’",
    common: ["Esqueleto", "vendue « epipremnoides »"],
    origin: "Cultivar d’un clone de serre — pas M. epipremnoides sauvage",
    difficulty: "Intermédiaire",
    kind: "cultivar",
    image: wiki("Monstera 'Esqueleto'.png"),
    credit: "Wikimedia Commons",
    summary: "Grande, très trouée. Nom de culture. L’epipremnoides vraie est une autre plante (Costa Rica, Panama).",
    description:
      "Le clone aux fenêtres énormes a été pris pour epipremnoides. Après comparaison, on l’a enregistré comme ‘Esqueleto’ (proche de lechleriana selon cette lecture). Grande liane, tuteur, lumière indirecte.",
    traits: ["Cultivar", "Pas epipremnoides"],
  }),
  wild({
    id: "adansonii-archipelago",
    name: "Monstera adansonii ‘Archipelago’",
    common: ["Archipelago"],
    origin: "Sélection horticole d’adansonii",
    image: wiki("Monstera adansonii - Mickaël Schauli - 4.jpg"),
    credit: "Wikimedia Commons — adansonii très trouée, nom commercial",
    kind: "cultivar",
    difficulty: "Facile",
    summary: "Nom de pépinière pour une adansonii très trouée. Pas une espèce.",
    description:
      "Wide form, narrow form, Archipelago : ce sont des étiquettes, pas des noms Kew. La plante reste une adansonii (trous au centre). Culture identique.",
    traits: ["Cultivar / nom commercial", "adansonii"],
  }),
  wild({
    id: "standleyana-var",
    name: "Monstera standleyana panachée",
    common: ["Cobra albo / aurea"],
    origin: "Sélections de standleyana",
    image: inat(653548135),
    credit: "iNaturalist",
    kind: "cultivar",
    difficulty: "Intermédiaire",
    summary: "Même espèce étroite, avec des secteurs crème ou jaunes. Toujours une Monstera, pas un philodendron.",
    description:
      "Les formes panachées se vendent cher sous « Cobra ». Botaniquement : standleyana. Le blanc/jaune est une mutation, avec les mêmes limites que sur deliciosa (brûlure, revert).",
    traits: ["Cultivar", "standleyana"],
  }),
  wild({
    id: "peru",
    name: "Philodendron opacum (vendu « Monstera Peru »)",
    common: ["Monstera Peru", "Karstenianum", "Green Galaxy"],
    family: "Araceae — genre Philodendron",
    origin: "Nicaragua → Équateur (Kew : P. opacum)",
    size: "Plutôt compacte, feuilles épaisses",
    difficulty: "Facile",
    kind: "lookalike",
    image: inat(346609002, "jpeg"),
    credit: "iNaturalist — Philodendron opacum",
    summary: "Malgré le nom, ce n’est pas une Monstera. Feuilles gaufrées, sans trou.",
    description:
      "Kew : Philodendron opacum. « Monstera karstenianum » n’est pas un nom valide. On arrose moins souvent qu’une deliciosa.",
    traits: ["Pas une Monstera", "P. opacum"],
  }),
  wild({
    id: "mini-monstera",
    name: "Rhaphidophora tetrasperma (vendue « Mini Monstera »)",
    common: ["Mini Monstera", "Ginny"],
    family: "Araceae — genre Rhaphidophora",
    origin: "Malaisie péninsulaire, sud de la Thaïlande — Asie, pas Amérique",
    image: wiki("Rhaphidophora tetrasperma.jpg"),
    credit: "Wikimedia Commons",
    difficulty: "Facile",
    kind: "lookalike",
    summary:
      "Petites feuilles découpées, vendue « mini Monstera ». Autre continent, autre genre.",
    description:
      "Kew accepte Rhaphidophora tetrasperma. Elle vient d’Asie du Sud-Est. La ressemblance avec une jeune deliciosa est un hasard de forme. Ce n’est ni Monstera minima, ni une deliciosa naine.",
    traits: ["Pas une Monstera", "Asie"],
  }),
];
